### ISSUE TITLE
Does not work on RG35XX classic

### ISSUE THREAD

**Issue by reverbrick** [MrJackSpade/RG35XX-Store#1]
It doesn't start. None of versions work.
Tested with updated GarlicOS provided with stockOS image and latest GarlicOS.
I can help debugging, but I cannot see any log...

**Comment by MrJackSpade** [comment]
Thank you for letting me know. Can you tell me what happens when you run the ARM-32 version?

Does it show some kind of "Loading splash", or hang for a minute, or do anything of note?

I can push an update that generates a log file if you're willing to try it.

**Comment by MrJackSpade** [comment]
This may be fixed with this latest update.

It might also not, but I have nothing else to go on
